In [ ]:
data = {

'Name': ['John', 'Anna', None, 'Linda', 'Sophia'],

'Age': [28, 24, 40, None, 25],

'Salary': [50000, 55000, 60000, 70000, 65000],

'Join Date': ['2015-03-15', '2017-07-01', '2018-01-12', '2016-08-05', '2019-11-19'],

'Department': ['HR', 'Finance', 'HR', 'IT', 'Finance'],

'Gender': ['Male', 'Female', 'Male', 'Female', 'Female']

}


df = pd.DataFrame(data)


1. How to fill missing values in a column with a specific value (e.g., 'Unknown' for Name)?

2. How to fill missing numerical values in a column with the mean of that column?

3. How can rows with missing values be removed from a Pandas DataFrame?


------------------------------------------------------------------------------------------------------------------------


data = {

'Name': ['John', 'Anna', 'Peter', 'Linda', 'Sophia'],

'Age': [28, 24, 40, 33, 25],

'Salary': [50000, 55000, 60000, 70000, 65000],

'Join Date': ['2015-03-15', '2017-07-01', '2018-01-12', '2016-08-05', '2019-11-19'],

'Department': ['HR', 'Finance', 'HR', 'IT', 'Finance'],

'Gender': ['Male', 'Female', 'Male', 'Female', 'Female']

}


df = pd.DataFrame(data)


1. How to convert a column to a specific format (e.g., convert a date column to datetime format)?

2. How to filter the data based on a condition (e.g., age > 25)?

3. How to filter the data based on a specific value (e.g., get all rows where Name is 'Anna')?

4. How to select specific columns in the DataFrame (e.g., Name and Salary columns)?

5. How to select specific rows (e.g., first 3 rows)?

6. How to get the rows by index positions (e.g., using .iloc[])?

7. How to sort the data by a specific column in ascending order (e.g., Age)?

8. How to sort the data by a column in descending order (e.g., Salary)?

9. How to group data by a specific column (e.g., Age) and calculate the average salary for each group?

10. How to aggregate multiple statistics on a column (e.g., calculate mean, max, and min salary by Age)?

11. How to apply a function to modify a column (e.g., increasing the salary by 10%) using apply()?

12. How to add a new column to the DataFrame (e.g., adding a column for Bonus)?

13. How to rename columns in the DataFrame (e.g., renaming Join Date to Joining Date)?

14. How to drop a specific column from the DataFrame (e.g., dropping the Bonus column)?

15. How to add a new categorical column, Job Role, to the DataFrame?

16. How to calculate the average salary for each department?

17. How to determine which department has the most employees?

18. How to find which department has the most female employees?